### ISSUE TITLE
[walproposer] Possible inconsistency in connection establisment logic

### ISSUE THREAD

**Issue by funbringer** [zenithdb/postgres#64]
The following pieces of code seem to be at odds with each other:

https://github.com/zenithdb/postgres/blob/59ad940fcbd7a7b26de3957cfc8f34b3f95a8fe6/src/backend/replication/walproposer.c#L850-L851

https://github.com/zenithdb/postgres/blob/59ad940fcbd7a7b26de3957cfc8f34b3f95a8fe6/src/backend/replication/walproposer.c#L142

@arssher @sharnoff feel free to close this if I get it wrong or once the problem has been fixed.

**Comment by sharnoff** [comment]
I don't really know tbh. The first one is directly related to [this logic](https://github.com/zenithdb/zenith/blob/8517d9696d7675c7085961f56d309bc5b7c2fd93/walkeeper/src/wal_service.rs#L46-51) in wal_service. But I don't know why that's not necessary for the second snippet. Perhaps @lubennikovaav might know?

In any case though, the connection logic is completely reworked in #60, so I probably wouldn't worry too much about it.

**Comment by arssher** [comment]
Yes, let's just close this as we won't have raw sockets anymore soon. Thanks for noticing.
